### ISSUE TITLE
Import to web worker

### ISSUE THREAD

**Issue by XBDRX** [insane-jo/talib-wasm#5]
Have you tried to import the wasm to a webworker? I'm looking into that at the moment.  I'm new to Emscripten and using Rollup instead of Webpack.

I'm happy to submit a PR once I figure it out but wanted to check if you'd already tried & rejected the idea, or could alert me to any potential problems you've encountered.

**Comment by insane-jo** [comment]
Hello, @XBDRX. Yes, I have few projects with talib-wasm in webworkers. But I use webpack instead of rollup.

You can see webpack config example in this [commit](https://github.com/insane-jo/talib-wasm/issues/1#issuecomment-593311260). And there browser example call. Take a look on externals part in config, may be that will help you.

**Comment by insane-jo** [comment]
I'll close issue. If you have questions - fell free to reopen it
